### ISSUE TITLE
由于翻译问题，部分题目与原书不符，可以参考译者的勘误

### ISSUE THREAD

**Issue by Kratos0902** [hjcapple/reading-sicp#1]
https://www.math.pku.edu.cn/teachers/qiuzy/books/sicp/errata.htm

**Comment by hjcapple** [comment]
根据勘误表，练习3.70，b) 问中的「i 或者 j 可以被 2，3 或者 5 整除」。应该修正为「i 和 j 都不能被 2, 3, 5 整除」。
修正后的条件「i 和 j 都不能被 2, 3, 5 整除」作为了问 c) 补充完整。
https://github.com/hjcapple/reading-sicp/commit/908e70a6ab7f621dc0b52c2130e4bf02f8d50a41
