### ISSUE TITLE
3.47中22行是不是可以去掉

### ISSUE THREAD

**Issue by guagua777** [hjcapple/reading-sicp#3]
https://github.com/hjcapple/reading-sicp/blob/master/chapter_3/exercise_3_47.scm
这个里面的22的(lock 'release)是不是应该去掉，也就是n=0的时候，为什么要先释放锁，然后再重试呢，不是应该直接重试吗？

**Comment by hjcapple** [comment]
封装好的 mutex，其  'acquire  和  'release 方法需要配对。
第 16 行中，调用了 (lock 'acquire)，假如在 try 之前，第 22 行没有相应调用 (lock 'release)。'acquire 和 'release 就没有配对了。
就类似 C++ 的 std::mutex，调用了 lock(对应这里的 'acquire)，必须有相应的 unlock(对应这里的 ‘release)，不然上锁后没有对应释放，就产生同步问题了。

**Comment by hjcapple** [comment]
> https://github.com/hjcapple/reading-sicp/blob/master/chapter_3/exercise_3_47.scm
> 这个里面的22的(lock 'release)是不是应该去掉，也就是n=0的时候，为什么要先释放锁，然后再重试呢，不是应该直接重试吗？

封装好的 mutex，其  'acquire  和  'release 方法需要配对。
第 16 行中，调用了 (lock 'acquire)，假如在 try 之前，第 22 行没有相应调用 (lock 'release)。'acquire 和 'release 就没有配对了。
就类似 C++ 的 std::mutex，调用了 lock(对应这里的 'acquire)，必须有相应的 unlock(对应这里的 ‘release)，不然上锁后没有对应释放，就产生同步问题了。

**Comment by hjcapple** [comment]
封装好的 mutex，其  'acquire  和  'release 方法需要配对。
第 16 行中，调用了 (lock 'acquire)，假如在 try 之前，第 22 行没有相应调用 (lock 'release)。'acquire 和 'release 就没有配对了。
就类似 C++ 的 std::mutex，调用了 lock(对应这里的 'acquire)，必须有相应的 unlock(对应这里的 ‘release)，不然上锁后没有对应释放，就产生同步问题了。

**Comment by guagua777** [comment]
嗯，懂了，谢谢
