### ISSUE TITLE
请问练习1.16中 定义的test模块如何使用？

### ISSUE THREAD

**Issue by Aka-JingTanShiZhe** [hjcapple/reading-sicp#5]
即使手动单独调用test中的过程也还是不行，请问test模块要怎么运行
>Welcome to DrRacket, version 8.6 [cs].
Language: racket, with debugging; memory limit: 128 MB.
 (for-loop 0 10 check)
. . for-loop: undefined;
 cannot reference an identifier before its definition
>

**Comment by hjcapple** [comment]
test 模块的代码是单元测试，你点击 Run 的时候，就会自动执行。并不需要手动调用。
假如单元测试成功，控制台不会有提示。但假如 Run 时单元测试失败，控制台会出现红色的 FAILURE。更多信息，你搜索一下 rackunit。
