### ISSUE TITLE
练习1.28中的代码，是不是有问题？

### ISSUE THREAD

**Issue by Aka-JingTanShiZhe** [hjcapple/reading-sicp#6]
博主是否有检验过答案，有运行成功吗？ 
我怀疑这题做的不对，理由是 notrival？过程的实参不应为base，而应该为上一次fast-prime?迭代产生的结果。

**Comment by hjcapple** [comment]
代码都经过运行测试的，应该没有错。你调试一下 fmiller-rabin-test 的调用，当触发  (expmod base exp m)  时，这里的参数 m 传的待测试的数，也就是题目中的 n; base 传的是 < n 的一个随机数，也就是题目中的 a。
